name: Test cross compile

on:
  push:
    branches:
      - "feature/cross-platform-build" # for testing
    # tags:
    #   - "v*"

permissions:
  contents: write
  id-token: write

jobs:
  linux-runners:
    name: Linux – ${{ matrix.platform }}
    strategy:
      matrix:
        platform:
          - x86_64-linux-musl
          - aarch64-linux-musl
          - x86_64-linux
          - aarch64-linux
    uses: ./.github/workflows/_linux_cross_compile.yml
    with:
      platform: ${{ matrix.platform }}
      dry-run: 'true'
