name: Test cross compile

on:
  push:
    branches:
      - "feature/cross-platform-build" # for testing

jobs:
  linux-runners:
    name: Linux – ${{ matrix.platform }}
    strategy:
      matrix:
        platform:
          - x86_64-linux-musl
          - aarch64-linux-musl
          - x86_64-linux
          - aarch64-linux
    uses: ./.github/workflows/_linux_cross_compile.yml
    with:
      platform: ${{ matrix.platform }}

  macos-runners:
    name: MacOS - ${{ matrix.platform }}
    strategy:
      matrix:
        include:
          - platform: x86_64-darwin
            runner: macos-13
          - platform: arm64-darwin
            runner: macos-14
    uses: ./.github/workflows/_macos_cross_compile.yml
    with:
      platform: ${{ matrix.platform }}
      runner: ${{ matrix.runner }}

  display-gem:
    name: Display gems
    needs: [linux-runners, macos-runners]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
          bundler-cache: true

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          pattern: gem-*
          path: ./artifacts
          merge-multiple: true

      - name: Show artifacts
        run: |
          sudo apt-get update
          sudo apt-get install -y tree
          tree ./artifacts
