name: Release Mongory

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  id-token: write

jobs:
  linux-runners:
    name: Linux – ${{ matrix.platform }}
    strategy:
      matrix:
        platform:
          - x86_64-linux-musl
          - aarch64-linux-musl
          - x86_64-linux
          - aarch64-linux
    uses: ./.github/workflows/_linux_cross_compile.yml
    with:
      platform: ${{ matrix.platform }}
      dry-run: 'false'

  release-gem:
    name: Release (source gem) via official action
    needs: linux-runners
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
          bundler-cache: true

      - name: Release (source gem) via official action
        uses: rubygems/release-gem@v1
