name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '2.6.10'

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Install build tools
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential
    - name: Build native extension (mongory-core)
      run: bundle exec rake build_all
    - name: Run the default task
      run: bundle exec rake
